os: osx
language: node_js
node_js:
- 10.13.0
install:
- npm install hexo-cli -g
- npm install hexo-generator-feed --save
- npm install hexo --save
script:
- hexo generate
after_success:
- sh build.sh
